language: go

go:
  - 1.16

before_install:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.24.0

env:
  CODECOV_TOKEN: cnf.CODECOV_TOKEN
#env:
#  - GO111MODULE=on
#
#install: true

script:
  - go get -t -v ./...
  - go mod vendor
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - ls -l
  # - go test -v -mod=readonly -covermode=count -coverprofile=coverage.out ./...
  - go test -v -mod=mod -covermode=count -coverprofile=coverage.out ./...
  - go mod vendor
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $CODECOV_TOKEN
  - make lint
