language: go

go:
  - 1.8.x
  - tip

before_install:
  - go get -t -v ./...

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)


#name: Test and coverage
#
#on: [push, pull_request]
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#        with:
#          fetch-depth: 2
#      - uses: actions/setup-go@v2
#        with:
#          go-version: '1.16'
#      - name: Run coverage
#        run: go test -race -coverprofile=coverage.txt -covermode=atomic
#      - name: Upload coverage to Codecov
#        run: bash <(curl -s https://codecov.io/bash)